FROM node:22-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS build
COPY . /app
WORKDIR /app
RUN rm -f pnpm-lock.yaml package-lock.json
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --no-frozen-lockfile --ignore-scripts && \
    pnpm approve-builds && \
    pnpm install --no-frozen-lockfile
RUN pnpm build

FROM base
COPY --from=build /app /app
WORKDIR /app
EXPOSE 3000
CMD [ "pnpm", "start" ]
