FROM node:22-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS build
COPY . /app
WORKDIR /app
RUN rm -f pnpm-lock.yaml package-lock.json
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --no-frozen-lockfile --ignore-scripts && \
    pnpm approve-builds && \
    pnpm install --no-frozen-lockfile
RUN pnpm build

FROM base AS prod-deps
WORKDIR /app
COPY package.json ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --prod --no-frozen-lockfile --ignore-scripts

FROM base
WORKDIR /app
COPY --from=build /app/.output ./.output
COPY --from=build /app/src/db ./src/db
COPY --from=build /app/drizzle.config.ts ./
COPY --from=build /app/package.json ./
COPY --from=prod-deps /app/node_modules ./node_modules
EXPOSE 3000
CMD [ "pnpm", "start" ]
